"""Detects mismatches between the database and the tl/ files before export."""

from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from core.storage.repositories import ProjectMetaRepository, TranslationUnitRepository

META_SAVED_AT = "tl_saved_at"
META_SAVED_MTIME = "tl_saved_mtime"

_SQLITE_TIME_FORMAT = "%Y-%m-%d %H:%M:%S"


@dataclass
class ExportSyncState:
    """Discrepancies found between the tl/ files and the database."""

    never_saved: bool
    unsaved_units: int
    externally_modified: bool

    @property
    def in_sync(self) -> bool:
        """Whether the tl/ files hold every translation kept in database."""
        return not (self.never_saved or self.unsaved_units or self.externally_modified)


def latest_rpy_mtime(tl_dir: Path) -> float:
    """Return the most recent modification time among the .rpy files of tl_dir.

    Args:
        tl_dir: Directory holding the translation files generated by the SDK.

    Returns:
        The highest st_mtime found, or 0.0 if the directory holds no .rpy file.
    """
    return max((path.stat().st_mtime for path in tl_dir.rglob("*.rpy")), default=0.0)


def record_save(meta: ProjectMetaRepository, tl_dir: Path) -> None:
    """Store the disk and clock state right after translations were written.

    The timestamp is formatted like the updated_at column maintained by the
    database trigger (UTC, one second resolution), so both can later be
    compared as plain strings.

    Args:
        meta: Per-project key/value store.
        tl_dir: Directory the translations were written into.
    """
    meta.set(META_SAVED_MTIME, str(latest_rpy_mtime(tl_dir)))
    meta.set(META_SAVED_AT, datetime.now(UTC).strftime(_SQLITE_TIME_FORMAT))


def check_sync(
    tl_dir: Path,
    meta: ProjectMetaRepository,
    units: TranslationUnitRepository,
) -> ExportSyncState:
    """Compare the tl/ files on disk with the translations held in database.

    The SDK fills every generated block with a copy of the source text, so
    files that were never written to still export as a full archive, only
    in the source language. All three discrepancies are therefore silent
    without this check.

    Args:
        tl_dir: Directory holding the translation files to be exported.
        meta: Per-project key/value store holding the last save markers.
        units: Repository used to count translations edited since that save.

    Returns:
        The discrepancies an export may need to warn about.
    """
    saved_at = meta.get(META_SAVED_AT)
    if not saved_at:
        return ExportSyncState(
            never_saved=True,
            unsaved_units=0,
            externally_modified=False,
        )

    saved_mtime = meta.get(META_SAVED_MTIME)
    return ExportSyncState(
        never_saved=False,
        unsaved_units=units.count_modified_since(saved_at),
        externally_modified=latest_rpy_mtime(tl_dir) > float(saved_mtime or 0.0),
    )
